AlloyDemo/Models/Pages/GDPRApiDemoPage.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using AlloyDemo.Models;
using AlloyDemo.Models.Pages;
using System.ComponentModel.DataAnnotations;

namespace AlloyDemo
{
    [SiteContentType(GUID = "0877D78B-8673-4CF9-9F78-3E50C30C4479",
        GroupName = AlloyDemo.Global.GroupNames.Specialized,
        DisplayName = "Find GDPR API Demo Page")]
    public class GDPRApiDemoPage : SitePageData, ISearchPage
    {
    }
}

AlloyDemo/Controllers/GDPRApiDemoPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using EPiServer.Find;
using EPiServer.Find.Statistics;
using AlloyDemo.Controllers;
using AlloyDemo.Models.ViewModels;
using System.Web.Mvc;

namespace AlloyDemo.Controllers
{
    public class GDPRApiDemoPageController : PageControllerBase<GDPRApiDemoPage>
    {
        private readonly IStatisticsClient _statisticsClient;
        private readonly ITrackSanitizer _trackSanitizer;
        private readonly ITrackSanitizerPatternRepository _trackSanitizerPatternRepository;

        public GDPRApiDemoPageController(IClient searchClient)
        {
            _statisticsClient = searchClient.Statistics();
            _trackSanitizer = searchClient.TrackSanitizer();
            _trackSanitizerPatternRepository = _trackSanitizer.TrackSaniziterRepository;
        }

        [ValidateInput(false)]
        public ViewResult Index(GDPRApiDemoPage currentPage, string q)
        {
            var model = new GDPRDemoModel(currentPage);

            if (!string.IsNullOrWhiteSpace(q))
            {
                var getResult = _statisticsClient.StatisticsGetGDPR(q);
                model.GetHits = getResult.Hits;
            }

            var gdprPattern = _trackSanitizerPatternRepository.GetAll();

            model.PlainTextFilterPatterns = gdprPattern?.Where(t => t.PatternType == TrackSanitizerFilterType.PlainText).Select(i => i.PatternString).ToList();
            model.RegexFilterPatterns = gdprPattern?.Where(t => t.PatternType == TrackSanitizerFilterType.Regex).Select(i => i.PatternString).ToList();
            model.WildcardFilterPatterns = gdprPattern?.Where(t => t.PatternType == TrackSanitizerFilterType.Wildcard).Select(i => i.PatternString).ToList();

            return View("Index", model);
        }

        [HttpPost, ActionName("Index")]
        [ValidateInput(false)]
        public ViewResult Delete(GDPRApiDemoPage currentPage, string q)
        {
            var model = new GDPRDemoModel(currentPage);
            if (!string.IsNullOrWhiteSpace(q))
            {
                var deleteResult = _statisticsClient.StatisticsDeleteGDPR(q);
                model.DeleteStatus = deleteResult.Status;
            }
            else
            {
                model.DeleteStatus = "Statistics is GDPR compliance.";
            }

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public void Save(GDPRApiDemoPage currentPage, string plaintextFilter, string wildcardFilter, string regexFilter)
        {
            _trackSanitizerPatternRepository.DeleteAll();

            var filterPatterns = new List<TrackSanitizerPattern>();
            var plaintextPatterns = string.IsNullOrEmpty(plaintextFilter)
                ? new List<TrackSanitizerPattern>()
                : plaintextFilter.Split(new[] {"\r\n"}, StringSplitOptions.None)
                    .Where(i => !string.IsNullOrEmpty(i.Trim()))
                    .Select(t => new TrackSanitizerPattern {PatternString = t, PatternType = TrackSanitizerFilterType.PlainText});
            var wildcardPatterns = string.IsNullOrEmpty(wildcardFilter)
                ? new List<TrackSanitizerPattern>()
                : wildcardFilter.Split(new[] {"\r\n"}, StringSplitOptions.None)
                    .Where(i => !string.IsNullOrEmpty(i.Trim()))
                    .Select(t => new TrackSanitizerPattern {PatternString = t, PatternType = TrackSanitizerFilterType.Wildcard});
            var regexPatterns = string.IsNullOrEmpty(regexFilter)
                ? new List<TrackSanitizerPattern>()
                : regexFilter.Split(new[] {"\r\n"}, StringSplitOptions.None)
                    .Where(i => !string.IsNullOrEmpty(i.Trim()))
                    .Select(t => new TrackSanitizerPattern {PatternString = t, PatternType = TrackSanitizerFilterType.Regex});

            filterPatterns.AddRange(plaintextPatterns);
            filterPatterns.AddRange(wildcardPatterns);
            filterPatterns.AddRange(regexPatterns);

            _trackSanitizerPatternRepository.Add(filterPatterns);
        }
    }
}

AlloyDemo/Views/GDPRapiDemoPage/Index.cshtml
@using System.Web.Mvc.Html
@using EPiServer.Editor
@using EPiServer.Find
@using AlloyDemo
@using AlloyDemo.Models.ViewModels
@using Newtonsoft.Json
@model GDPRDemoModel

<div class="page-header">
    <h1>GDPR API demo page</h1>
</div>

<div class="row">
    <div class="span8">
        @using (Html.BeginForm(null, null, Model.Layout.SearchActionUrl, PageEditing.PageIsInEditMode ? FormMethod.Post : FormMethod.Get, new { @class = "form-inline" }))
        {
            <input id="srchTxt" type="text" tabindex="1" name="q" value="@Model.GDPRGetQuery" class="search-query" placeholder="keyword for track query" />
            <button type="submit" class="searchButton"></button>
        }

        @if (Model.GetHits != null)
        {
            <div class="row">
                <div class="span8">
                    <p>Total: @Model.GetHits.Count</p>
                </div>
            </div>
            <div class="row">
                <div class="span8 SearchResults">
                    @foreach (var hit in Model.GetHits)
                {
                        <div class="listResult">
                            <pre>@JsonConvert.SerializeObject(hit)</pre>
                        </div>
                    }
                </div>
            </div>
        }

        @if (!string.IsNullOrEmpty(Model.DeleteStatus))
        {
            <div class="span8 DeleteResult">
                <pre>Delete Status: @Model.DeleteStatus</pre>
            </div>
        }

        <div class="row">
            <div class="span8">
                @using (Html.BeginForm(null, null, Model.Layout.SearchActionUrl, FormMethod.Post))
                {
                    <input id="deleteTxt" type="text" tabindex="1" name="q" value="@Model.GDPRGetQuery" class="search-query" style="display: none" placeholder="keyword for query" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                }
            </div>
        </div>
    </div>
    <div class="span4">
        @Html.Partial("_TrackSanitizerPatternsOverview")
    </div>
</div>

AlloyDemo/Views/GDPRapiDemoPage/_TrackSanitizerPatternsOverview.cshtml
<h3>Track sanitizer pattern overview</h3>
@using (Html.BeginForm("Save", "GDPRApiDemoPage", null, FormMethod.Post, new { id = "PatternForm" }))
{
    <div class="row">
        <div class="span4">
            <div>
                <h4>Plain Text Pattern</h4>
                <textarea cols="40" rows="5" name="plaintextFilter" placeholder="Patterns are separated by line break">@Html.Raw(Model.PlainTextFilterPatterns != null ? string.Join("\r\n", Model.PlainTextFilterPatterns) : string.Empty)</textarea>
            </div>
            <div>
                <h4>Wildcard Pattern</h4>
                <textarea cols="40" rows="5" name="wildcardFilter" placeholder="Patterns are separated by line break">@Html.Raw(Model.WildcardFilterPatterns != null ? string.Join("\r\n", Model.WildcardFilterPatterns) : string.Empty)</textarea>
            </div>
            <div>
                <h4>Regex Pattern</h4>
                <textarea cols="40" rows="5" name="regexFilter" placeholder="Patterns are separated by line break">@Html.Raw(Model.RegexFilterPatterns != null ? string.Join("\r\n", Model.RegexFilterPatterns) : string.Empty)</textarea>
            </div>
            <button type="submit" class="btn btn-success">Save patterns</button>
            <div id="result"></div>
        </div>
    </div>
}

<script>
    $(function () {
        $('#PatternForm').submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    $('#result').html(`<div class="alert alert-success" id="PatternFormAlert">Patterns updated.</div>`);
                    setTimeout(function () {
                        $('#PatternFormAlert').fadeOut().remove();
                    }, 3000);
                }
            });
            return false;
        });
    });
</script>